<?php

namespace Database\Seeders;

use App\Models\DocumentProperty;
use App\Models\DocumentType;
use DB;
use Illuminate\Database\Seeder;

class DocumentPropertySeeder extends Seeder
{
    public function run(): void
    {
        DocumentProperty::resetAutoIncrement();

        $document_properties = array(
            1 => [
                array(
                    "key" => "1_debitoren_kreditorennummer",
                    "name" => "Debitoren-/Kreditorennummer",
                    "type" => "Contact Number",
                    "rules" => "required",
                    "order" => 2,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "1_kunden_lieferantenname",
                    "name" => "Kunden-/Lieferantenname",
                    "type" => "Contact Name",
                    "rules" => "required",
                    "order" => 1,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "1_rechnungsnummer",
                    "name" => "Rechnungsnummer",
                    "type" => "Text",
                    "rules" => "required",
                    "order" => 3,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "1_vorgangsnummer",
                    "name" => "Vorgangsnummer",
                    "type" => "Ticket",
                    "rules" => "required",
                    "order" => 4,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "1_rechnungssumme_brutto",
                    "name" => "Rechnungssumme (Brutto)",
                    "type" => "Integer",
                    "rules" => "required",
                    "order" => 5,
                    "is_name" => 0,
                    "active" => 1,
                ),
                array(
                    "key" => "1_umsatzsteuer",
                    "name" => "Umsatzsteuer",
                    "type" => "Integer",
                    "rules" => "required",
                    "order" => 6,
                    "is_name" => 0,
                    "active" => 1,
                ),
                array(
                    "key" => "1_falligkeit",
                    "name" => "Fälligkeit",
                    "type" => "Date",
                    "rules" => "required",
                    "order" => 7,
                    "is_name" => 0,
                    "active" => 1,
                ),
            ],
            2 => [
                array(
                    "key" => "2_debitoren_kreditorennummer",
                    "name" => "Debitoren-/Kreditorennummer",
                    "type" => "Contact Number",
                    "rules" => "required",
                    "order" => 2,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "2_kunden_lieferantenname",
                    "name" => "Kunden-/Lieferantenname",
                    "type" => "Contact Name",
                    "rules" => "required",
                    "order" => 1,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "2_lieferscheinnummer",
                    "name" => "Lieferscheinnummer",
                    "type" => "Text",
                    "rules" => "required",
                    "order" => 3,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "2_vorgangsnummer",
                    "name" => "Vorgangsnummer",
                    "type" => "Ticket",
                    "rules" => "required",
                    "order" => 4,
                    "is_name" => 1,
                    "active" => 1,
                ),
            ],
            3 => [
                array(
                    "key" => "3_debitoren_kreditorennummer",
                    "name" => "Debitoren-/Kreditorennummer",
                    "type" => "Contact Number",
                    "rules" => "required",
                    "order" => 2,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "3_kunden_lieferantenname",
                    "name" => "Kunden-/Lieferantenname",
                    "type" => "Contact Name",
                    "rules" => "required",
                    "order" => 1,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "3_auftragsbestatigungsnummer",
                    "name" => "Auftragsbestätigungsnummer",
                    "type" => "Text",
                    "rules" => "required",
                    "order" => 3,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "3_vorgangsnummer",
                    "name" => "Vorgangsnummer",
                    "type" => "Ticket",
                    "rules" => "required",
                    "order" => 4,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "3_rechnungssumme_brutto",
                    "name" => "Rechnungssumme (Brutto)",
                    "type" => "Integer",
                    "rules" => "required",
                    "order" => 5,
                    "is_name" => 0,
                    "active" => 1,
                ),
                array(
                    "key" => "3_umsatzsteuer",
                    "name" => "Umsatzsteuer",
                    "type" => "Integer",
                    "rules" => NULL,
                    "order" => 6,
                    "is_name" => 0,
                    "active" => 1,
                ),
                array(
                    "key" => "3_kalkulierte_stundenzahl",
                    "name" => "Kalkulierte Stundenzahl",
                    "type" => "Integer",
                    "rules" => NULL,
                    "order" => 7,
                    "is_name" => 0,
                    "active" => 1,
                ),
                array(
                    "key" => "3_kalkulierter_materialeinsatz",
                    "name" => "Kalkulierter Materialeinsatz",
                    "type" => "Integer",
                    "rules" => NULL,
                    "order" => 8,
                    "is_name" => 0,
                    "active" => 1,
                ),
            ],

            4 => [
                array(
                    "key" => "4_debitoren_kreditorennummer",
                    "name" => "Debitoren-/Kreditorennummer",
                    "type" => "Contact Number",
                    "rules" => "required",
                    "order" => 2,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "4_kunden_lieferantenname",
                    "name" => "Kunden-/Lieferantenname",
                    "type" => "Contact Name",
                    "rules" => "required",
                    "order" => 1,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "4_angebotsnummer",
                    "name" => "Angebotsnummer",
                    "type" => "Text",
                    "rules" => "required",
                    "order" => 3,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "4_vorgangsnummer",
                    "name" => "Vorgangsnummer",
                    "type" => "Ticket",
                    "rules" => "required",
                    "order" => 4,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "4_rechnungssumme_brutto",
                    "name" => "Rechnungssumme (Brutto)",
                    "type" => "Integer",
                    "rules" => "required",
                    "order" => 5,
                    "is_name" => 0,
                    "active" => 1,
                ),
                array(
                    "key" => "4_umsatzsteuer",
                    "name" => "Umsatzsteuer",
                    "type" => "Integer",
                    "rules" => NULL,
                    "order" => 6,
                    "is_name" => 0,
                    "active" => 1,
                ),
            ],

            6 => [
                array(
                    "key" => "6_debitoren_kreditorennummer",
                    "name" => "Debitoren-/Kreditorennummer",
                    "type" => "Contact Number",
                    "rules" => "required",
                    "order" => 2,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "6_kunden_lieferantenname",
                    "name" => "Kunden-/Lieferantenname",
                    "type" => "Contact Name",
                    "rules" => "required",
                    "order" => 1,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "6_vorgangsnummer",
                    "name" => "Vorgangsnummer",
                    "type" => "Ticket",
                    "rules" => "required",
                    "order" => 3,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "6_berichtnummer",
                    "name" => "Berichtnummer",
                    "type" => "Text",
                    "rules" => "required",
                    "order" => 4,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "6_rechnungsnummer",
                    "name" => "Rechnungsnummer",
                    "type" => "Text",
                    "rules" => "required",
                    "order" => 5,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "6_arbeitszeit",
                    "name" => "Arbeitszeit",
                    "type" => "Text",
                    "rules" => NULL,
                    "order" => 6,
                    "is_name" => 0,
                    "active" => 1,
                ),
            ],

            12 => [
                array(
                    "key" => "12_absender",
                    "name" => "Absender",
                    "type" => "Text",
                    "rules" => "required",
                    "order" => 1,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "12_grund_freitexteingabe",
                    "name" => "Grund: Freitexteingabe",
                    "type" => "Text",
                    "rules" => "required",
                    "order" => 2,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "12_freitexteingabe",
                    "name" => "Freitexteingabe",
                    "type" => "Text",
                    "rules" => NULL,
                    "order" => 3,
                    "is_name" => 0,
                    "active" => 1,
                ),
            ],

            13 => [
                array(
                    "key" => "13_absender",
                    "name" => "Absender",
                    "type" => "Text",
                    "rules" => "required",
                    "order" => 1,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "13_grund_freitexteingabe",
                    "name" => "Grund: Freitexteingabe",
                    "type" => "Text",
                    "rules" => "required",
                    "order" => 2,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "13_freitexteingabe",
                    "name" => "Freitexteingabe",
                    "type" => "Text",
                    "rules" => NULL,
                    "order" => 3,
                    "is_name" => 0,
                    "active" => 1,
                ),
            ],

            14 => [
                array(
                    "key" => "14_debitoren_kreditorennummer",
                    "name" => "Debitoren-/Kreditorennummer",
                    "type" => "Contact Number",
                    "rules" => "required",
                    "order" => 2,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "14_kunden_lieferantenname",
                    "name" => "Kunden-/Lieferantenname",
                    "type" => "Contact Name",
                    "rules" => "required",
                    "order" => 1,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "14_vorgangsnummer",
                    "name" => "Vorgangsnummer",
                    "type" => "Ticket",
                    "rules" => "required",
                    "order" => 4,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "14_rechnungssumme_brutto",
                    "name" => "Rechnungssumme (Brutto)",
                    "type" => "Integer",
                    "rules" => "required",
                    "order" => 5,
                    "is_name" => 0,
                    "active" => 1,
                ),
                array(
                    "key" => "14_rechnungsnummer",
                    "name" => "Rechnungsnummer",
                    "type" => "Text",
                    "rules" => "required",
                    "order" => 3,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "14_zugehorige_rechnungsnummer",
                    "name" => "Zugehörige Rechnungsnummer",
                    "type" => "Text",
                    "rules" => "required",
                    "order" => 98,
                    "is_name" => 0,
                    "active" => 0,
                ),
                array(
                    "key" => "14_verlust_aus_gutschrift",
                    "name" => "Verlust aus Gutschrift",
                    "type" => "Text",
                    "rules" => "required",
                    "order" => 99,
                    "is_name" => 0,
                    "active" => 0,
                ),
                array(
                    "key" => "14_umsatzsteuer",
                    "name" => "Umsatzsteuer",
                    "type" => "Integer",
                    "rules" => "required",
                    "order" => 6,
                    "is_name" => 0,
                    "active" => 1,
                ),
                array(
                    "key" => "14_falligkeit",
                    "name" => "Fälligkeit",
                    "type" => "Date",
                    "rules" => "required",
                    "order" => 7,
                    "is_name" => 0,
                    "active" => 1,
                ),
            ],

            16 => [
                array(
                    "key" => "16_vorgangsnummer",
                    "name" => "Vorgangsnummer",
                    "type" => "Ticket",
                    "rules" => "required",
                    "order" => 4,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "16_rechnungssumme_brutto",
                    "name" => "Rechnungssumme (Brutto)",
                    "type" => "Integer",
                    "rules" => "required",
                    "order" => 5,
                    "is_name" => 0,
                    "active" => 1,
                ),
                array(
                    "key" => "16_rechnungsnummer",
                    "name" => "Rechnungsnummer",
                    "type" => "Text",
                    "rules" => "required",
                    "order" => 3,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "16_zugehorige_rechnungsnummer",
                    "name" => "Zugehörige Rechnungsnummer",
                    "type" => "Text",
                    "rules" => "required",
                    "order" => 99,
                    "is_name" => 0,
                    "active" => 0,
                ),
                array(
                    "key" => "16_falligkeit",
                    "name" => "Fälligkeit",
                    "type" => "Date",
                    "rules" => "required",
                    "order" => 7,
                    "is_name" => 0,
                    "active" => 1,
                ),
                array(
                    "key" => "16_debitoren_kreditorennummer",
                    "name" => "Debitoren-/Kreditorennummer",
                    "type" => "Contact Number",
                    "rules" => "required",
                    "order" => 2,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "16_kunden_lieferantenname",
                    "name" => "Kunden-/Lieferantenname",
                    "type" => "Contact Name",
                    "rules" => "required",
                    "order" => 1,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "16_umsatzsteuer",
                    "name" => "Umsatzsteuer",
                    "type" => "Integer",
                    "rules" => "required",
                    "order" => 6,
                    "is_name" => 0,
                    "active" => 1,
                ),
            ],

            17 => [
                array(
                    "key" => "17_freitexteingabe",
                    "name" => "Freitexteingabe",
                    "type" => "Text",
                    "rules" => "required",
                    "order" => 2,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "17_datum",
                    "name" => "Datum",
                    "type" => "Date",
                    "rules" => "required",
                    "order" => 1,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "17_vorgangsnummer",
                    "name" => "Vorgangsnummer",
                    "type" => "Ticket",
                    "rules" => "required",
                    "order" => 3,
                    "is_name" => 0,
                    "active" => 1,
                ),
            ],

            18 => [
                array(
                    "key" => "18_debitorennummer",
                    "name" => "Debitorennummer",
                    "type" => "Contact Number",
                    "rules" => "required",
                    "order" => 2,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "18_kundenname",
                    "name" => "Kundenname",
                    "type" => "Contact Name",
                    "rules" => "required",
                    "order" => 1,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "18_wv_nummer",
                    "name" => "WV-Nummer",
                    "type" => "Text",
                    "rules" => "required",
                    "order" => 3,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "18_interval_in_monaten",
                    "name" => "Interval in Monaten",
                    "type" => "Integer",
                    "rules" => "required",
                    "order" => 4,
                    "is_name" => 0,
                    "active" => 1,
                ),
                array(
                    "key" => "18_kundigungsfrist_in_monaten",
                    "name" => "Kündigungsfrist in Monaten",
                    "type" => "Integer",
                    "rules" => "required",
                    "order" => 5,
                    "is_name" => 0,
                    "active" => 1,
                ),
                array(
                    "key" => "18_abschlussdatum",
                    "name" => "Abschlussdatum",
                    "type" => "Date",
                    "rules" => "required",
                    "order" => 6,
                    "is_name" => 0,
                    "active" => 1,
                ),
                array(
                    "key" => "18_rechnungssumme_brutto",
                    "name" => "Rechnungssumme (Brutto)",
                    "type" => "Integer",
                    "rules" => "required",
                    "order" => 7,
                    "is_name" => 0,
                    "active" => 1,
                ),
                array(
                    "key" => "18_umsatzsteuer",
                    "name" => "Umsatzsteuer",
                    "type" => "Integer",
                    "rules" => NULL,
                    "order" => 8,
                    "is_name" => 0,
                    "active" => 1,
                ),
            ],

            19 => [
                array(
                    "key" => "19_falligkeit",
                    "name" => "Fälligkeit",
                    "type" => "Date",
                    "rules" => "required",
                    "order" => 8,
                    "is_name" => 0,
                    "active" => 1,
                ),
                array(
                    "key" => "19_mahnungsnummer",
                    "name" => "Mahnungsnummer",
                    "type" => "Text",
                    "rules" => "required",
                    "order" => 3,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "19_vorgangsnummer",
                    "name" => "Vorgangsnummer",
                    "type" => "Ticket",
                    "rules" => "required",
                    "order" => 5,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "19_debitoren_kreditorennummer",
                    "name" => "Debitoren-/Kreditorennummer",
                    "type" => "Contact Number",
                    "rules" => "required",
                    "order" => 2,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "19_kunden_lieferantenname",
                    "name" => "Kunden-/Lieferantenname",
                    "type" => "Contact Name",
                    "rules" => "required",
                    "order" => 1,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "19_rechnungsnummer",
                    "name" => "Rechnungsnummer",
                    "type" => "Text",
                    "rules" => "required",
                    "order" => 4,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "19_rechnungssumme_brutto",
                    "name" => "Rechnungssumme (Brutto)",
                    "type" => "Integer",
                    "rules" => "required",
                    "order" => 6,
                    "is_name" => 0,
                    "active" => 1,
                ),
                array(
                    "key" => "19_umsatzsteuer",
                    "name" => "Umsatzsteuer",
                    "type" => "Integer",
                    "rules" => NULL,
                    "order" => 7,
                    "is_name" => 0,
                    "active" => 1,
                ),
            ],

            20 => [
                array(
                    "key" => "20_kunden_lieferantenname",
                    "name" => "Kunden-/Lieferantenname",
                    "type" => "Contact Name",
                    "rules" => "required",
                    "order" => 1,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "20_avisnummer",
                    "name" => "Avisnummer",
                    "type" => "Text",
                    "rules" => "required",
                    "order" => 3,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "20_debitoren_kreditorennummer",
                    "name" => "Debitoren-/Kreditorennummer",
                    "type" => "Contact Number",
                    "rules" => "required",
                    "order" => 2,
                    "is_name" => 1,
                    "active" => 1,
                ),
            ],

            21 => [
                array(
                    "key" => "21_mitarbeiternamen",
                    "name" => "Mitarbeiternamen",
                    "type" => "Text",
                    "rules" => "required",
                    "order" => 1,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "21_meldung_von",
                    "name" => "Meldung von",
                    "type" => "Date",
                    "rules" => "required",
                    "order" => 2,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "21_meldung_bis",
                    "name" => "Meldung bis",
                    "type" => "Date",
                    "rules" => "required",
                    "order" => 3,
                    "is_name" => 1,
                    "active" => 1,
                ),
            ],

            22 => [
                array(
                    "key" => "22_debitoren_kreditorennummer",
                    "name" => "Debitoren-/Kreditorennummer",
                    "type" => "Contact Number",
                    "rules" => "required",
                    "order" => 2,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "22_kunden_lieferantenname",
                    "name" => "Kunden-/Lieferantenname",
                    "type" => "Contact Name",
                    "rules" => "required",
                    "order" => 1,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "22_vorgangsnummer",
                    "name" => "Vorgangsnummer",
                    "type" => "Ticket",
                    "rules" => "required",
                    "order" => 3,
                    "is_name" => 1,
                    "active" => 1,
                ),
                array(
                    "key" => "22_freitexteingabe",
                    "name" => "Freitexteingabe",
                    "type" => "Text",
                    "rules" => "required",
                    "order" => 4,
                    "is_name" => 1,
                    "active" => 1,
                ),
            ],
        );

        foreach ($document_properties as $documentTypeId => $documentTypeProperties) {
            foreach ($documentTypeProperties as $property) {
                $property['document_type_id'] = $documentTypeId;
                DocumentProperty::create($property);
            }
        }
    }
}
