<?php

namespace Tests\Fakes;

use App\Lexoffice\LexofficeApi;
use File;

class LexofficeApiFake extends LexofficeApi
{
    public function create_quotation($data, $finalized = false)
    {
        return json_decode(fixture('Lexoffice/create_quotation.json'));
    }

    public function get_quotation($uuid)
    {
        return json_decode(fixture('Lexoffice/get_quotation.json'));
    }

    public function get_pdf($type, $uuid, $filename): bool
    {
        $dir = str($filename)->beforeLast('/')->value();
        File::makeDirectory($dir);

        File::put($filename, 'test_content');

        return true;
    }

    public function create_event($event, $callback = false)
    {
        return parent::create_event($event, $callback); // TODO: Change the autogenerated stub
    }

    public function get_events_all()
    {
        return parent::get_events_all(); // TODO: Change the autogenerated stub
    }

    public function delete_event($uuid)
    {
        return parent::delete_event($uuid); // TODO: Change the autogenerated stub
    }

    public function upload_file($file)
    {
        return parent::upload_file($file); // TODO: Change the autogenerated stub
    }

    public function get_contact($uuid)
    {
        dd('todo');
    }

    public function save_pdf_by_uuid($uuid, $filename): bool
    {
        dd('todo');
    }

    public function get_invoice($uuid)
    {
        dd('todo');
    }

    public function get_down_payment_invoice($uuid)
    {
        dd('todo');
    }

    public function get_voucher_files($uuid, $filename_prefix): array
    {
        dd('todo');
    }
}
